// Movie Dataset with 30+ movies including URLs and trailer links
const movieDataset = [
  {
    id: 1,
    title: "The Dark Knight",
    category: "Action",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    rating: 9.0,
    image: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500",
    movieUrl: "https://www.imdb.com/title/tt0468569/",
    trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    isTop10: true,
    isSeries: false,
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    recommended: [2, 3, 15]
  },
  {
    id: 2,
    title: "Inception",
    category: "Sci-fi",
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into a CEO's mind.",
    rating: 8.8,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    movieUrl: "https://www.imdb.com/title/tt1375666/",
    trailerUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    isTop10: true,
    isSeries: false,
    cast: ["Leonardo DiCaprio", "Marion Cotillard", "Tom Hardy", "Elliot Page"],
    recommended: [1, 4, 16]
  },
  {
    id: 3,
    title: "Pulp Fiction",
    category: "Thriller",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    rating: 8.9,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt0110912/",
    trailerUrl: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
    isTop10: true,
    isSeries: false,
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    recommended: [1, 5, 17]
  },
  {
    id: 4,
    title: "The Shawshank Redemption",
    category: "Drama",
    description: "Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
    rating: 9.3,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0111161/",
    trailerUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
    isTop10: true,
    isSeries: false,
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    recommended: [2, 6, 18]
  },
  {
    id: 5,
    title: "The Godfather",
    category: "Drama",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    rating: 9.2,
    image: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500",
    movieUrl: "https://www.imdb.com/title/tt0068646/",
    trailerUrl: "https://www.youtube.com/watch?v=sY1S34973zA",
    isTop10: true,
    isSeries: false,
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
    recommended: [3, 4, 19]
  },
  {
    id: 6,
    title: "Forrest Gump",
    category: "Drama",
    description: "The presidencies of Kennedy and Johnson, Vietnam, Watergate, and other history unfold through the perspective of an Alabama man.",
    rating: 8.8,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt0109830/",
    trailerUrl: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    isTop10: true,
    isSeries: false,
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    recommended: [4, 5, 20]
  },
  {
    id: 7,
    title: "The Matrix",
    category: "Sci-fi",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    rating: 8.7,
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500",
    movieUrl: "https://www.imdb.com/title/tt0133093/",
    trailerUrl: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    isTop10: true,
    isSeries: false,
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    recommended: [2, 8, 21]
  },
  {
    id: 8,
    title: "Goodfellas",
    category: "Thriller",
    description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.",
    rating: 8.7,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0099685/",
    trailerUrl: "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
    isTop10: true,
    isSeries: false,
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
    recommended: [3, 5, 22]
  },
  {
    id: 9,
    title: "Fight Club",
    category: "Thriller",
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    rating: 8.8,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt0137523/",
    trailerUrl: "https://www.youtube.com/watch?v=qtRKdVHc-cE",
    isTop10: true,
    isSeries: false,
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
    recommended: [3, 8, 23]
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    category: "Action",
    description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.",
    rating: 8.9,
    image: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500",
    movieUrl: "https://www.imdb.com/title/tt0120737/",
    trailerUrl: "https://www.youtube.com/watch?v=V75dMMIW2B4",
    isTop10: true,
    isSeries: false,
    cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom", "Sean Bean"],
    recommended: [1, 7, 24]
  },
  {
    id: 11,
    title: "Superbad",
    category: "Comedy",
    description: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
    rating: 7.6,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0829482/",
    trailerUrl: "https://www.youtube.com/watch?v=4eaZ_48ZYog",
    isTop10: false,
    isSeries: false,
    cast: ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse", "Emma Stone"],
    recommended: [12, 13, 25]
  },
  {
    id: 12,
    title: "The Hangover",
    category: "Comedy",
    description: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.",
    rating: 7.7,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt1119646/",
    trailerUrl: "https://www.youtube.com/watch?v=tcdUhdOlz9M",
    isTop10: false,
    isSeries: false,
    cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis", "Justin Bartha"],
    recommended: [11, 13, 26]
  },
  {
    id: 13,
    title: "Anchorman",
    category: "Comedy",
    description: "Ron Burgundy is San Diego's top-rated newsman in the male-dominated broadcasting of the 1970s, but that's all about to change.",
    rating: 7.2,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0357413/",
    trailerUrl: "https://www.youtube.com/watch?v=NJQ4qEWm9lU",
    isTop10: false,
    isSeries: false,
    cast: ["Will Ferrell", "Christina Applegate", "Paul Rudd", "Steve Carell"],
    recommended: [11, 12, 27]
  },
  {
    id: 14,
    title: "Step Brothers",
    category: "Comedy",
    description: "Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry.",
    rating: 6.9,
    image: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500",
    movieUrl: "https://www.imdb.com/title/tt0838283/",
    trailerUrl: "https://www.youtube.com/watch?v=CewJ-ihIqaM",
    isTop10: false,
    isSeries: false,
    cast: ["Will Ferrell", "John C. Reilly", "Mary Steenburgen", "Richard Jenkins"],
    recommended: [11, 13, 28]
  },
  {
    id: 15,
    title: "Tropic Thunder",
    category: "Comedy",
    description: "A group of self-absorbed actors set out to make the most expensive war film ever, but get thrown into a real-life jungle adventure.",
    rating: 7.0,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0942385/",
    trailerUrl: "https://www.youtube.com/watch?v=Yj-wc9qugGY",
    isTop10: false,
    isSeries: false,
    cast: ["Ben Stiller", "Jack Black", "Robert Downey Jr.", "Tom Cruise"],
    recommended: [12, 14, 29]
  },
  {
    id: 16,
    title: "Zoolander",
    category: "Comedy",
    description: "At the end of his career, a clueless fashion model is brainwashed to kill the Prime Minister of Malaysia.",
    rating: 6.5,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt0196229/",
    trailerUrl: "https://www.youtube.com/watch?v=E6Dh7ESAd5s",
    isTop10: false,
    isSeries: false,
    cast: ["Ben Stiller", "Owen Wilson", "Christine Taylor", "Will Ferrell"],
    recommended: [13, 15, 30]
  },
  {
    id: 17,
    title: "Dumb and Dumber",
    category: "Comedy",
    description: "Two dim-witted friends embark on a cross-country trip to return a briefcase full of money to its rightful owner.",
    rating: 7.3,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0109686/",
    trailerUrl: "https://www.youtube.com/watch?v=l13yPhimE3o",
    isTop10: false,
    isSeries: false,
    cast: ["Jim Carrey", "Jeff Daniels", "Lauren Holly", "Mike Starr"],
    recommended: [11, 16, 31]
  },
  {
    id: 18,
    title: "The Conjuring",
    category: "Horror",
    description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    rating: 7.5,
    image: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500",
    movieUrl: "https://www.imdb.com/title/tt1457767/",
    trailerUrl: "https://www.youtube.com/watch?v=k10ETZ41q5o",
    isTop10: false,
    isSeries: false,
    cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor", "Ron Livingston"],
    recommended: [19, 20, 32]
  },
  {
    id: 19,
    title: "Get Out",
    category: "Horror",
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness becomes a nightmare.",
    rating: 7.7,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500",
    movieUrl: "https://www.imdb.com/title/tt5052448/",
    trailerUrl: "https://www.youtube.com/watch?v=DzfpyUB60YY",
    isTop10: false,
    isSeries: false,
    cast: ["Daniel Kaluuya", "Allison Williams", "Catherine Keener", "Bradley Whitford"],
    recommended: [18, 21, 33]
  },
  {
    id: 20,
    title: "A Quiet Place",
    category: "Horror",
    description: "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
    rating: 7.5,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt6644200/",
    trailerUrl: "https://www.youtube.com/watch?v=WR7cc5t7tv8",
    isTop10: false,
    isSeries: false,
    cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds", "Noah Jupe"],
    recommended: [18, 19, 34]
  },
  {
    id: 21,
    title: "Hereditary",
    category: "Horror",
    description: "A grieving family is haunted by tragedy and disturbing secrets in this psychological horror film.",
    rating: 7.3,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    movieUrl: "https://www.imdb.com/title/tt7784604/",
    trailerUrl: "https://www.youtube.com/watch?v=V6wWKNij_1M",
    isTop10: false,
    isSeries: false,
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro", "Gabriel Byrne"],
    recommended: [19, 20, 35]
  },
  {
    id: 22,
    title: "The Notebook",
    category: "Romance",
    description: "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom.",
    rating: 7.8,
    image: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500",
    movieUrl: "https://www.imdb.com/title/tt0332280/",
    trailerUrl: "https://www.youtube.com/watch?v=FC6biTjEyZw",
    isTop10: false,
    isSeries: false,
    cast: ["Ryan Gosling", "Rachel McAdams", "James Garner", "Gena Rowlands"],
    recommended: [23, 24, 25]
  },
  {
    id: 23,
    title: "Titanic",
    category: "Romance",
    description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    rating: 7.8,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0120338/",
    trailerUrl: "https://www.youtube.com/watch?v=2e-eXJ6HgkQ",
    isTop10: false,
    isSeries: false,
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Gloria Stuart"],
    recommended: [22, 24, 26]
  },
  {
    id: 24,
    title: "La La Land",
    category: "Romance",
    description: "A jazz musician and an aspiring actress meet and fall in love in Los Angeles while pursuing their dreams.",
    rating: 8.0,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt3783958/",
    trailerUrl: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    isTop10: false,
    isSeries: false,
    cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
    recommended: [22, 23, 27]
  },
  {
    id: 25,
    title: "Casablanca",
    category: "Romance",
    description: "A cynical American expatriate struggles to decide whether or not he should help his former lover escape French Morocco.",
    rating: 8.5,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0034583/",
    trailerUrl: "https://www.youtube.com/watch?v=BkL9l7qovsE",
    isTop10: false,
    isSeries: false,
    cast: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid", "Claude Rains"],
    recommended: [22, 24, 28]
  },
  // Series
  {
    id: 26,
    title: "Breaking Bad",
    category: "Drama",
    description: "A high school chemistry teacher turned methamphetamine manufacturer partners with a former student.",
    rating: 9.5,
    image: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500",
    movieUrl: "https://www.imdb.com/title/tt0903747/",
    trailerUrl: "https://www.youtube.com/watch?v=HhesaQXLuRY",
    isTop10: false,
    isSeries: true,
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Dean Norris"],
    recommended: [27, 28, 29]
  },
  {
    id: 27,
    title: "Game of Thrones",
    category: "Action",
    description: "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros.",
    rating: 9.3,
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0944947/",
    trailerUrl: "https://www.youtube.com/watch?v=rlR4PJn8b8I",
    isTop10: false,
    isSeries: true,
    cast: ["Emilia Clarke", "Peter Dinklage", "Kit Harington", "Lena Headey"],
    recommended: [26, 28, 30]
  },
  {
    id: 28,
    title: "Stranger Things",
    category: "Sci-fi",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments and supernatural forces.",
    rating: 8.7,
    image: "https://images.unsplash.com/photo-1489599349066-7cfbc4fe02aa?w=500",
    movieUrl: "https://www.imdb.com/title/tt4574334/",
    trailerUrl: "https://www.youtube.com/watch?v=b9EkMc79ZSU",
    isTop10: false,
    isSeries: true,
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
    recommended: [26, 27, 31]
  },
  {
    id: 29,
    title: "The Office",
    category: "Comedy",
    description: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes and inappropriate behavior.",
    rating: 8.9,
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500",
    movieUrl: "https://www.imdb.com/title/tt0386676/",
    trailerUrl: "https://www.youtube.com/watch?v=LHOtME2DL4g",
    isTop10: false,
    isSeries: true,
    cast: ["Steve Carell", "John Krasinski", "Jenna Fischer", "Rainn Wilson"],
    recommended: [30, 31, 32]
  },
  {
    id: 30,
    title: "Friends",
    category: "Comedy",
    description: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
    rating: 8.9,
    image: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500",
    movieUrl: "https://www.imdb.com/title/tt0108778/",
    trailerUrl: "https://www.youtube.com/watch?v=hDNNmeeJs1Q",
    isTop10: false,
    isSeries: true,
    cast: ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matt LeBlanc"],
    recommended: [29, 31, 33]
  }
];

// Customer feedback data
const customerFeedback = [
  {
    id: 1,
    name: "Sarah Johnson",
    rating: 5,
    feedback: "Amazing selection of movies and series! The streaming quality is excellent and the interface is so user-friendly. Highly recommend!",
    profileIcon: "👩"
  },
  {
    id: 2,
    name: "Mike Chen",
    rating: 5,
    feedback: "Best streaming service I've used. Great variety of content and the wishlist feature makes it easy to keep track of what I want to watch.",
    profileIcon: "👨"
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    rating: 4,
    feedback: "Love the red and black theme! Very sleek design. The search functionality works perfectly and I can always find what I'm looking for.",
    profileIcon: "👩‍🦱"
  },
  {
    id: 4,
    name: "David Kim",
    rating: 5,
    feedback: "Incredible 4K quality and the download feature for offline viewing is a game-changer. Worth every penny of the subscription!",
    profileIcon: "👨‍💼"
  },
  {
    id: 5,
    name: "Lisa Thompson",
    rating: 4,
    feedback: "Great customer service and an extensive library. The category filtering makes browsing so much easier. Really impressed!",
    profileIcon: "👩‍🔬"
  },
  {
    id: 6,
    name: "James Wilson",
    rating: 5,
    feedback: "The carousel feature showcasing top movies is brilliant! Clean interface and fast loading times. Definitely my go-to streaming platform.",
    profileIcon: "👨‍🎨"
  }
];